### ISSUE TITLE
Release Builds?

### ISSUE THREAD

**Issue by DavidBuchanan314** [ZoomTen/flappy-bird-rebuild#1]
Thanks so much for figuring this out!

Any chance you could share the rebuilt apk? (through github releases perhaps) I'm feeling very lazy ;P

**Comment by Timmyy23** [comment]
> Thanks so much for figuring this out!
> 
> Any chance you could share the rebuilt apk? (through github releases perhaps) I'm feeling very lazy ;P

Did you ever get the apk or can you explain how to rebate it?

**Comment by ZoomTen** [comment]
Sorry for the late reply, a patched APK should be available on releases now
